version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: unless-stopped
    ports:
      - 65432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=9TKSxmjBWyrH
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    restart: unless-stopped
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_ignite
    depends_on: 
      - database_ignite

volumes:
  pgdata:
    driver: local